[project]
name = "prjct-devef-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastembed>=0.7.4",
    "hdbscan>=0.8.41",
    "qdrant-client>=1.16.2",
    "sentence-transformers>=5.2.2",
]
